_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.1
            "6": 4.44.2
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-x86_64
batch_size:
    value: 12
context_length:
    value: 512
dropout:
    value: 0.1
hidden_size:
    value: 768
max_learning_rate:
    value: 0.0006
num_heads:
    value: 12
num_layers:
    value: 12
